server:
    directory: "/usr/local/etc/unbound"
    username: "unbound"

    port: 5553
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

    # #default logging
    verbosity: 1
    log-queries: no
    log-replies: no
    val-log-level: 0

    #detailed logging
    # verbosity: 5
    # log-queries: yes
    # log-replies: yes
    # val-log-level: 2
    
    chroot: "/usr/local/etc/unbound"
    logfile: "log/unbound.log"
    pidfile: "log/unbound.pid"

    # IP that unbound is bound to / listens on
    interface: 0.0.0.0
    access-control: 0.0.0.0/0 allow
    # Explicitly allow unbound to query localhost, where our nameservers are (default value is "yes")
    # do-not-query-localhost: no

    # trust anchor for the root zone - update this and uncomment to enable DNSSEC validation
    trust-anchor: ".	IN	DS	54956 13 2 9bbab42b11b319a8f7d3975737d9fae2a0c3497bfb7c03ff9fd20ea205a66b01"

    root-hints: "/usr/local/etc/unbound/root.hints"

    remote-control:
        control-enable: yes
        control-interface: 0.0.0.0
        control-port: 5443
        control-use-cert: no
